blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.BlogPostList.as_view(), name='blog_list'),
    path('<int:pk>/', views.blog_post_detail_view, name='blog_detail'),
    path('<int:pk>/update', views.BlogPostUpdate.as_view(), name='blog_update'),
    path('<int:pk>/post-delete', views.BlogPostDelete.as_view(), name='blog_delete'),
    path('<int:pk>/comment-delete', views.BlogCommentDelete.as_view(), name='comment_delete'),
    path('create/', views.blog_post_create, name='blog_create'),

]

books/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('needed_books/', views.NeededBooksListView.as_view(), name='needed_books'),
    path('added_books/', views.AddedBooksListView.as_view(), name='added_books'),
    path('<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('create/', views.book_create_view, name='book_create'),
    path('<int:pk>/delete', views.BookDeleteView.as_view(), name='book_delete'),
    path('<int:pk>/update', views.BookUpdateView.as_view(), name='book_update'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('rosetta/', include('rosetta.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.translation import gettext as _


class Book(models.Model):
    NEED_OR_ADD_CHOICES = (
        ('need', _('needed')),
        ('add', _('added')),
    )
    MAJOR_CHOICES = (
        ('riazi', _('riazi')),
        ('tajrobi', _('tajrobi')),
        ('ensani', _('ensani')),
        ('general', _('general')),
        ('other', _('other')),
    )

    GRADE_CHOICES = (
        ('ten', _('tenth')),
        ('ele', _('eleventh')),
        ('twe', _('twelfth')),
        ('alg', _('all grades')),
        ('oth', _('other')),

    )
    LESSON_CHOICES = (
        ('calculus', _('calculus')),
        ('physics', _('physics')),
        ('chemistry', _('chemistry')),
        ('geometry', _('geometry')),
        ('statistics and probability', _('statistics and probability')),
        ('discrete math', _('discrete math')),
        ('biology', _('biology')),
        ('persian', _('persian')),
        ('arabic', _('arabic')),
        ('english', _('english')),
        ('religion and life', _('religion and life')),
        ('other', _('other')),
    )

    title = models.CharField(max_length=200, blank=False, verbose_name=_('title'))
    book_official_link = models.TextField(blank=False, verbose_name=_('book official link'))
    publisher = models.CharField(max_length=100, blank=False, verbose_name=_('publisher'))
    description = models.TextField(blank=True, verbose_name=_('description'))
    major = models.CharField(max_length=10, choices=MAJOR_CHOICES, blank=False, verbose_name=_('major'))
    grade = models.CharField(max_length=3, choices=GRADE_CHOICES, blank=False, verbose_name=_('grade'))
    lesson = models.CharField(max_length=30, choices=LESSON_CHOICES, blank=False, verbose_name=_('lesson'))
    need_or_add = models.CharField(max_length=5, choices=NEED_OR_ADD_CHOICES, blank=False, verbose_name=_('need or add'))
    year = models.IntegerField(verbose_name=_('publish year'))
    date_created = models.DateField(auto_now_add=True)
    time_created = models.TimeField(auto_now_add=True)
    user = models.ForeignKey(get_user_model(), related_name='books', on_delete=models.CASCADE)
    is_active = models.BooleanField()
    book_cover = models.ImageField(upload_to='book_covers/', blank=True, verbose_name=_('book cover'))

    def __str__(self):
        return f"{self.title} , {self.grade}"

    def get_absolute_url(self):
        return reverse('book_detail', args=[self.id])

books/forms.py
from django import forms

from .models import Book


class BookCreateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = (
            'title',
            'publisher',
            'lesson',
            'grade',
            'book_cover',
            'major',
            'need_or_add',
            'year',
            'book_official_link',
            'description',
        )


class BookUpdateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = (
            'title',
            'publisher',
            'lesson',
            'grade',
            'book_cover',
            'major',
            'need_or_add',
            'year',
            'book_official_link',
            'description',
        )

books/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

from .models import Book
from .forms import BookUpdateForm, BookCreateForm


class NeededBooksListView(generic.ListView):
    model = Book
    template_name = 'books/needed_books.html'
    context_object_name = 'books'

    def get_queryset(self):
        return Book.objects.filter(need_or_add=Book.NEED_OR_ADD_CHOICES[0][0], is_active=True).order_by(
            '-date_created')


class AddedBooksListView(generic.ListView):
    model = Book
    template_name = 'books/added_books.html'
    context_object_name = 'books'

    def get_queryset(self):
        return Book.objects.all().filter(need_or_add=Book.NEED_OR_ADD_CHOICES[1][0], is_active=True).order_by(
            '-date_created')


class BookDetailView(generic.DetailView, UserPassesTestMixin):
    model = Book
    template_name = 'books/book_detail.html'

    def test_func(self):
        obj = self.get_object()
        if self.request.user.is_superuser:
            return True
        else:
            return obj.user == self.request.user


@login_required
def book_create_view(request):
    if request.method == "POST":
        create_form = BookCreateForm(request.POST, request.FILES)
        if create_form.is_valid():
            new_book = create_form.save(commit=False)
            new_book.user = request.user
            new_book.is_active = False
            new_book.save()
            create_form = BookCreateForm()
    else:
        create_form = BookCreateForm()
    return render(request, 'books/book_create_view.html', {
        'form': create_form,
    })


class BookUpdateView(generic.UpdateView, UserPassesTestMixin, LoginRequiredMixin):
    model = Book
    template_name = 'books/book_update_view.html'
    success_url = reverse_lazy('home')
    form_class = BookUpdateForm

    def test_func(self):
        obj = self.get_object()
        if self.request.user.is_superuser:
            return True
        else:
            return obj.user == self.request.user


class BookDeleteView(generic.DeleteView, LoginRequiredMixin, UserPassesTestMixin):
    model = Book
    template_name = 'books/book_delete_view.html'
    success_url = reverse_lazy('home')

    def test_func(self):
        obj = self.get_object()
        if self.request.user.is_superuser:
            return True
        else:
            return obj.user == self.request.user

books/templates/books/added_books.html
{% extends '_base.html' %}

{% block title %}کتاب های مورد نیاز{% endblock title %}


{% block nav-links %}
    <li><a href="{% url 'home' %}" class="nav-link px-2 text-secondary">خانه</a></li>
    {#                    <li><a href="{% url 'users' %}" class="nav-link px-2 text-secondary navhover">کتاب دوستان</a></li>#}
    <li><a href="{% url 'home' %}#about" class="nav-link px-2 text-secondary ">درباره ما</a></li>
    <li><a href="{% url 'home' %}#contact" class="nav-link px-2 text-secondary">ارتباط با ما</a></li>
    <li><a href="{% url 'blog_list' %}" class="nav-link px-2 text-secondary ">بلاگ</a></li>
    <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle text-dark border-bottom border-dark" href="#" role="button" data-bs-toggle="dropdown"
           aria-expanded="false">
            کتاب ها
        </a>
        <ul class="dropdown-menu">

            <li><a href="{% url 'added_books' %}" class="nav-link px-2 text-dark ">کتاب های اضافه شده</a></li>
            <li><a href="{% url 'needed_books' %}" class="nav-link px-2 text-secondary ">کتاب های درخواستی</a></li>
        </ul>
    </li>
{% endblock nav-links %}

{% block page-content %}


    <div class="container">
        <div class="row">
            <div class="col-3">
                <div class="card shadow-sm">
                    <div class="card-header">
                        فیلتر
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">پایه</li>
                        <li class="list-group-item">درس</li>
                        <li class="list-group-item">...</li>
                    </ul>
                </div>
            </div>
            <div class="col-9">
                {% for book in books %}
                    <div class="card shadow-sm">
                        <h5 class="card-header">{{ book.user.username }} | {{ book.get_grade_display }}</h5>
                        <div class="card-body">
                            <h5 class="card-title">{{ book.get_lesson_display }}</h5>
                            <h6 class="card-title text-muted">ایجاد شده در تاریخ : {{ book.date_created }}</h6>
                            <p class="card-text">{{ book.description|truncatewords:25 }}</p>
                            <a href="{{ book.get_absolute_url }}" class="btn btn-primary text-left">مشاهده جزئیات</a>
                        </div>
                    </div>
                {% endfor %}


            </div>

        </div>
    </div>



{% endblock page-content %}

books/templates/books/book_create_view.html
{% extends '_base_blog.html' %}

{% load crispy_forms_tags %}

{% block page-title %}
    ایجاد درخواست جدید
{% endblock %}

{% block nav-links %}
    <li><a href="{% url 'home' %}" class="nav-link px-2 text-secondary">خانه</a></li>
    {#                    <li><a href="{% url 'users' %}" class="nav-link px-2 text-secondary navhover">کتاب دوستان</a></li>#}
    <li><a href="{% url 'home' %}#about" class="nav-link px-2 text-secondary ">درباره ما</a></li>
    <li><a href="{% url 'home' %}#contact" class="nav-link px-2 text-secondary ">ارتباط با ما</a></li>
    <li><a href="{% url 'blog_list' %}" class="nav-link px-2 text-secondary">بلاگ</a></li>
    <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle text-dark border-bottom border-dark" href="#" role="button"
           data-bs-toggle="dropdown"
           aria-expanded="false">
            کتاب ها
        </a>
        <ul class="dropdown-menu">
            {% if book.need_or_add == 'add' %}

                <li><a href="{% url 'added_books' %}" class="nav-link px-2 text-dark border-bottom border-dark">کتاب های
                    اضافه
                    شده</a></li>
            {% else %}
                <li><a href="{% url 'added_books' %}" class="nav-link px-2 text-secondary">کتاب های اضافه شده</a></li>
            {% endif %}
            {% if book.need_or_add == 'need' %}
                <li><a href="{% url 'needed_books' %}" class="nav-link px-2 text-dark border-bottom border-dark">کتاب
                    های
                    درخواستی</a></li>
            {% else %}
                <li><a href="{% url 'needed_books' %}" class="nav-link px-2 text-secondary ">کتاب های درخواستی</a></li>
            {% endif %}
        </ul>
    </li>

{% endblock nav-links %}

{% block page-content %}
    <div class="container mt-4" dir="rtl">
        <div class="row">
            <div class="col-9">
                <div class="card shadow my-3">
                    <h5 class="card-header bg-primary text-light px-5">ایجاد درخواست جدید</h5>
                    <div class="px-5 pt-3 pb-5">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-success mt-2">ایجاد</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-3">

                <div class="card my-3 shadow">
                    <h5 class="card-header bg-warning text-light">راهنما</h5>
                    <div class="card-body">
                        <p class="card-text">
                            عنوان و توضیحات کتاب مورد نظر خود را وارد کنید.
                            توجه داشته باشید که نوشته خود را در دسته بندی مناسب قرار دهید تا یافتن آن برای کاربران هموار
                            باشد. کتاب شما بعد از تایید ادمین به نمایش گذاشته میشود .
                        </p>
                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

books/templates/books/book_delete_view.html
{% extends '_base.html' %}

{% block page-title %}
    حذف درخواست
{% endblock page-title %}

{% block nav-links %}
    <li><a href="{% url 'home' %}" class="nav-link px-2 text-secondary">خانه</a></li>
    {#                    <li><a href="{% url 'users' %}" class="nav-link px-2 text-secondary navhover">کتاب دوستان</a></li>#}
    <li><a href="{% url 'home' %}#about" class="nav-link px-2 text-secondary ">درباره ما</a></li>
    <li><a href="{% url 'home' %}#contact" class="nav-link px-2 text-secondary ">ارتباط با ما</a></li>
    <li><a href="{% url 'blog_list' %}" class="nav-link px-2 text-secondary">بلاگ</a></li>
    <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle text-dark border-bottom border-dark" href="#" role="button" data-bs-toggle="dropdown"
           aria-expanded="false">
            کتاب ها
        </a>
        <ul class="dropdown-menu">
            {% if book.need_or_add == 'add' %}

                <li><a href="{% url 'added_books' %}" class="nav-link px-2 text-dark border-bottom border-dark">کتاب های
                    اضافه
                    شده</a></li>
            {% else %}
                <li><a href="{% url 'added_books' %}" class="nav-link px-2 text-secondary">کتاب های اضافه شده</a></li>
            {% endif %}
            {% if book.need_or_add == 'need' %}
                <li><a href="{% url 'needed_books' %}" class="nav-link px-2 text-dark border-bottom border-dark">کتاب
                    های
                    درخواستی</a></li>
            {% else %}
                <li><a href="{% url 'needed_books' %}" class="nav-link px-2 text-secondary ">کتاب های درخواستی</a></li>
            {% endif %}
        </ul>
    </li>
{% endblock nav-links %}

{% block page-content %}

    <div class="container">
        <div class="card">
            <div class="card-title">
                آیا مطمئنید ؟
            </div>
            <div class="card-subtitle">
                آیا از حذف این درخواست با عنوان {{ book.title }} مطمئنید ؟
            </div>
            <form method="post">
                {% csrf_token %}
                <button class="btn btn-danger">بله حذف شود</button>
                <a href="{% url 'home' %}" class="btn btn-primary">بازگشت به خانه</a>
            </form>
        </div>
    </div>

{% endblock page-content %}

books/templates/books/book_detail.html
{% extends '_base.html' %}

{% block page-title %}درخواست برای کتاب {{ book.title }}{% endblock page-title %}

{% block nav-links %}

    <li><a href="{% url 'home' %}" class="nav-link px-2 text-secondary">خانه</a></li>
    {#                    <li><a href="{% url 'users' %}" class="nav-link px-2 text-secondary navhover">کتاب دوستان</a></li>#}
    <li><a href="{% url 'home' %}#about" class="nav-link px-2 text-secondary ">درباره ما</a></li>
    <li><a href="{% url 'home' %}#contact" class="nav-link px-2 text-secondary ">ارتباط با ما</a></li>
    <li><a href="{% url 'blog_list' %}" class="nav-link px-2 text-secondary">بلاگ</a></li>
    <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle text-dark border-bottom border-dark" href="#" role="button"
           data-bs-toggle="dropdown"
           aria-expanded="false">
            کتاب ها
        </a>
        <ul class="dropdown-menu">
            {% if book.need_or_add == 'add' %}

                <li><a href="{% url 'added_books' %}" class="nav-link px-2 text-dark border-bottom border-dark">کتاب های
                    اضافه
                    شده</a></li>
            {% else %}
                <li><a href="{% url 'added_books' %}" class="nav-link px-2 text-secondary">کتاب های اضافه شده</a></li>
            {% endif %}
            {% if book.need_or_add == 'need' %}
                <li><a href="{% url 'needed_books' %}" class="nav-link px-2 text-dark border-bottom border-dark">کتاب
                    های
                    درخواستی</a></li>
            {% else %}
                <li><a href="{% url 'needed_books' %}" class="nav-link px-2 text-secondary ">کتاب های درخواستی</a></li>
            {% endif %}
        </ul>
    </li>


{% endblock nav-links %}



{% block page-content %}

    <div class="container mt-5" dir="rtl">
        <div class="">
            <div class="">
                <div class="d-flex justify-content-center">
                    <div class="row w-sm-75 w-100">
                        <div class="col-xs-12 col-md-3 d-flex justify-content-center">
                            <div>
                                {% if book.book_cover %}
                                    <img src="{{ book.book_cover.url }}"
                                         class="img-fluid rounded-start" alt="کتاب  {{ book.title }}">
                                {% else %}
                                    <img src="/media/book_covers/dsBuffer.jpg"
                                         class="img-fluid rounded-start" alt="کتاب {{ book.title }}"></a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-6 text-center text-md-end mt-md-1 mt-4">
                            <h1>{{ book.title }}</h1>
                            <h5 class="small my-1"><span class="text-muted">کاربر: </span>{{ book.user.username }}</h5>
                            <h5 class="small my-1"><span
                                    class="text-muted">تاریخ ایجاد : </span>{{ book.date_created }}</h5>
                            <h5 class="small my-1"><span class="text-muted">انتشارات: </span>{{ book.publisher }}</h5>
                            <h5 class="small my-1"><span class="text-muted">لینک کتاب در صفحه رسمی: </span><a
                                    href="{{ book.book_official_link }}" target="_blank">کلیک کنید</a></h5>
                        </div>
                        <div class="col-xs-12 col-md-3 d-flex flex-column">

                            {% if user == book.user or user.is_superuser %}

                                <a class="btn btn-warning" href="{% url 'book_update' book.id %}">به روز رسانی</a>
                                <br>
                                <a class="btn btn-danger" href="{% url 'book_delete' book.id %}">حذف درخواست</a>

                            {% endif %}
                            <a href="{% url 'out_view' book.user.id %}" class=" btn btn-primary mt-2">رفتن به صفحه کاربر</a>
                        </div>
                    </div>
                </div>

                <div class="d-flex justify-content-center">
                    <div class="my-3 p-5 w-sm-75 w-100">
                        {{ book.description|linebreaks }}
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock page-content %}

books/templates/books/book_update_view.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block page-title %}
به روز رسانی {{ book.title }}
{% endblock %}

{% block nav-links %}
    <li><a href="{% url 'home' %}" class="nav-link px-2 text-secondary">خانه</a></li>
    {#                    <li><a href="{% url 'users' %}" class="nav-link px-2 text-secondary navhover">کتاب دوستان</a></li>#}
    <li><a href="{% url 'home' %}#about" class="nav-link px-2 text-secondary ">درباره ما</a></li>
    <li><a href="{% url 'home' %}#contact" class="nav-link px-2 text-secondary ">ارتباط با ما</a></li>
    <li><a href="{% url 'blog_list' %}" class="nav-link px-2 text-secondary">بلاگ</a></li>
    <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle text-dark border-bottom border-dark" href="#" role="button" data-bs-toggle="dropdown"
           aria-expanded="false">
            کتاب ها
        </a>
        <ul class="dropdown-menu">
            {% if book.need_or_add == 'add' %}

                <li><a href="{% url 'added_books' %}" class="nav-link px-2 text-dark border-bottom border-dark">کتاب های
                    اضافه
                    شده</a></li>
            {% else %}
                <li><a href="{% url 'added_books' %}" class="nav-link px-2 text-secondary">کتاب های اضافه شده</a></li>
            {% endif %}
            {% if book.need_or_add == 'need' %}
                <li><a href="{% url 'needed_books' %}" class="nav-link px-2 text-dark border-bottom border-dark">کتاب
                    های
                    درخواستی</a></li>
            {% else %}
                <li><a href="{% url 'needed_books' %}" class="nav-link px-2 text-secondary ">کتاب های درخواستی</a></li>
            {% endif %}
        </ul>
    </li>
{% endblock nav-links %}

{% block page-content %}
<div class="container mt-4" dir="rtl">
    <div class="row">
        <div class="col-9">
            <div class="card shadow my-3">
                <h5 class="card-header bg-success text-light px-5">به روزرسانی {{ book.title }}</h5>
                <div class="px-5 pt-3 pb-5">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-success mt-2">به روز رسانی</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-3">

                <div class="card my-3 shadow">
                    <h5 class="card-header bg-warning text-light">راهنما</h5>
                    <div class="card-body">
                        <p class="card-text">
                            عنوان و توضیحات کتاب مورد نظر خود را وارد کنید.
                            توجه داشته باشید که نوشته خود را در دسته بندی مناسب قرار دهید تا یافتن آن برای کاربران هموار باشد.
                        </p>
                    </div>
                </div>

        </div>
    </div>
</div>

{% endblock page-content %}

books/templates/books/needed_books.html
{% extends '_base.html' %}

{% block title %}کتاب های مورد نیاز{% endblock title %}


{% block nav-links %}
    <li><a href="{% url 'home' %}" class="nav-link px-2 text-secondary">خانه</a></li>
    {#                    <li><a href="{% url 'users' %}" class="nav-link px-2 text-secondary navhover">کتاب دوستان</a></li>#}
    <li><a href="{% url 'home' %}#about" class="nav-link px-2 text-secondary ">درباره ما</a></li>
    <li><a href="{% url 'home' %}#contact" class="nav-link px-2 text-secondary ">ارتباط با ما</a></li>
    <li><a href="{% url 'blog_list' %}" class="nav-link px-2 text-secondary">بلاگ</a></li>
    <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle text-dark border-bottom border-dark" href="#" role="button" data-bs-toggle="dropdown"
           aria-expanded="false">
            کتاب ها
        </a>
        <ul class="dropdown-menu">

            <li><a href="{% url 'added_books' %}" class="nav-link px-2 text-secondary">کتاب های اضافه شده</a></li>
            <li><a href="{% url 'needed_books' %}" class="nav-link px-2 text-dark ">کتاب های درخواستی</a></li>
        </ul>
    </li>
{% endblock nav-links %}

{% block page-content %}

    <div class="container">
        <div class="row">
            <div class="col-3">
                <div class="card shadow-sm">
                    <div class="card-header">
                        فیلتر
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">پایه</li>
                        <li class="list-group-item">درس</li>
                        <li class="list-group-item">...</li>
                    </ul>
                </div>
            </div>
            <div class="col-9">
                {% for book in books %}
                    <div class="card shadow-sm">
                        <h5 class="card-header">{{ book.user.username }} | {{ book.get_grade_display }}</h5>
                        <div class="card-body">
                            <h5 class="card-title">{{ book.get_lesson_display }}</h5>
                            <h6 class="card-title text-muted">ایجاد شده در تاریخ : {{ book.date_created }}</h6>
                            <p class="card-text">{{ book.description|truncatewords:25 }}</p>
                            <a href="{{ book.get_absolute_url }}" class="btn btn-primary text-left">مشاهده جزئیات</a>
                        </div>
                    </div>
                {% endfor %}


            </div>

        </div>
    </div>



{% endblock page-content %}